// ─── Rôles ────────────────────────────────────────────────────────────────────
export const ROLES_META = {
    ADMIN:     { fr: 'Administrateur', ar: 'مدير',  color: '#ef4444', bg: '#fef2f2' },
    LAWYER:    { fr: 'Avocat',         ar: 'محامي', color: '#3b82f6', bg: '#eff6ff' },
    ASSISTANT: { fr: 'Assistant',      ar: 'مساعد', color: '#10b981', bg: '#ecfdf5' },
    CLIENT:    { fr: 'Client',         ar: 'موكل',  color: '#6b7280', bg: '#f9fafb' },
  };
  
  // ─── Statuts dossier ──────────────────────────────────────────────────────────
  export const STATUS_META = {
    ouvert:   { label: 'Ouvert',   color: '#10b981', bg: '#ecfdf5' },
    en_cours: { label: 'En cours', color: '#3b82f6', bg: '#eff6ff' },
    clôturé:  { label: 'Clôturé',  color: '#6b7280', bg: '#f3f4f6' },
  };
  
  export const CASE_TYPES = ['civil', 'pénal', 'commercial', 'administratif', 'autre'];
  
  // ─── Traductions ──────────────────────────────────────────────────────────────
  export const T = {
    fr: {
      title: 'Gestion des Utilisateurs',
      subtitle: 'Administration des accès et rôles',
      addUser: 'Ajouter un utilisateur',
      search: 'Rechercher...',
      allRoles: 'Tous les rôles',
      name: 'Nom complet',
      email: 'Adresse email',
      phone: 'Téléphone',
      role: 'Rôle',
      org: 'Organisation',
      createdAt: 'Créé le',
      actions: 'Actions',
      edit: 'Modifier',
      delete: 'Supprimer',
      save: 'Enregistrer',
      cancel: 'Annuler',
      password: 'Mot de passe',
      confirmDelete: 'Confirmer la suppression',
      deleteMsg: 'Cette action est irréversible. Voulez-vous vraiment supprimer',
      yes: 'Oui, supprimer',
      noData: 'Aucun utilisateur trouvé',
      loading: 'Chargement...',
      editUser: "Modifier l'utilisateur",
      newUser: 'Nouvel utilisateur',
      total: 'utilisateur(s)',
      page: 'Page',
      of: 'sur',
      required: 'Champ obligatoire',
      emailInvalid: 'Email invalide',
      pwdMin: 'Minimum 8 caractères',
      success: 'Opération réussie',
      error: 'Une erreur est survenue',
      logout: 'Déconnexion',
      login: 'Se connecter',
      loginSubtitle: 'Connexion à votre espace',
      stats: { total: 'Total', admins: 'Admins', lawyers: 'Avocats', clients: 'Clients' },
      cases: 'Dossiers',
      audiences: 'Audiences',
      documents: 'Documents',
      users: 'Utilisateurs',
    },
    ar: {
      title: 'إدارة المستخدمين',
      subtitle: 'إدارة الصلاحيات والأدوار',
      addUser: 'إضافة مستخدم',
      search: 'بحث...',
      allRoles: 'جميع الأدوار',
      name: 'الاسم الكامل',
      email: 'البريد الإلكتروني',
      phone: 'الهاتف',
      role: 'الدور',
      org: 'المنظمة',
      createdAt: 'تاريخ الإنشاء',
      actions: 'الإجراءات',
      edit: 'تعديل',
      delete: 'حذف',
      save: 'حفظ',
      cancel: 'إلغاء',
      password: 'كلمة المرور',
      confirmDelete: 'تأكيد الحذف',
      deleteMsg: 'هذا الإجراء لا يمكن التراجع عنه. هل تريد حقاً حذف',
      yes: 'نعم، احذف',
      noData: 'لا يوجد مستخدمون',
      loading: 'جار التحميل...',
      editUser: 'تعديل المستخدم',
      newUser: 'مستخدم جديد',
      total: 'مستخدم(ون)',
      page: 'صفحة',
      of: 'من',
      required: 'هذا الحقل مطلوب',
      emailInvalid: 'البريد الإلكتروني غير صالح',
      pwdMin: '٨ أحرف على الأقل',
      success: 'تمت العملية بنجاح',
      error: 'حدث خطأ ما',
      logout: 'تسجيل الخروج',
      login: 'تسجيل الدخول',
      loginSubtitle: 'الدخول إلى حسابك',
      stats: { total: 'الإجمالي', admins: 'المديرون', lawyers: 'المحامون', clients: 'الموكلون' },
      cases: 'القضايا',
      audiences: 'الجلسات',
      documents: 'الوثائق',
      users: 'المستخدمون',
    },
  };
  
  // ─── Mock data (utilisé si le serveur est absent) ─────────────────────────────
  export const MOCK_USERS = [
    { id: 1, nom: 'Karim Benali',       email: 'admin@benali.ma',   telephone: '0522-123456', role: 'ADMIN',     organization_id: 1, organization_name: 'Cabinet Benali & Associés', created_at: '2024-01-15' },
    { id: 2, nom: 'Leila Amrani',       email: 'lawyer@benali.ma',  telephone: '0522-234567', role: 'LAWYER',    organization_id: 1, organization_name: 'Cabinet Benali & Associés', created_at: '2024-02-01' },
    { id: 3, nom: 'Omar Chaoui',        email: 'assist@benali.ma',  telephone: '0522-345678', role: 'ASSISTANT', organization_id: 1, organization_name: 'Cabinet Benali & Associés', created_at: '2024-02-10' },
    { id: 4, nom: 'Hassan Idrissi',     email: 'client@benali.ma',  telephone: null,           role: 'CLIENT',    organization_id: 1, organization_name: 'Cabinet Benali & Associés', created_at: '2024-03-05' },
    { id: 5, nom: 'Nadia Tazi',         email: 'nadia@benali.ma',   telephone: '0661-445566', role: 'LAWYER',    organization_id: 1, organization_name: 'Cabinet Benali & Associés', created_at: '2024-03-12' },
    { id: 6, nom: 'Youssef Benjelloun', email: 'youssef@benali.ma', telephone: '0700-112233', role: 'CLIENT',    organization_id: 1, organization_name: 'Cabinet Benali & Associés', created_at: '2024-04-01' },
  ];